### ISSUE TITLE
DBD::mysql::db begin_work failed

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/Catmandu-DBI#32] opened 2021-01-21 09:59 UTC
We are seeing the following error message every morning in a worker using publication->add:

"DBD::mysql::db begin_work failed: Turning off AutoCommit failed at [....]/LibreCat/local/lib/perl5/Catmandu/Store/DBI.pm line 117"

Restarting the worker will fix the problem, but only until the next morning. The worker itself keeps running and working fine. Only writing to the db fails.

Google led me to this bug report: https://github.com/perl5-dbi/DBD-mysql/issues/202 which, unfortunately, does not have a solution yet.

Any idea on how to fix this? (As a temporary fix we are restarting workers nightly via cron.)

**Comment by petrakohorst** [comment] 2021-01-25 07:11
This is an error in our Orcid Worker.

The worker automatically imports new records from our users' Orcid profiles into our local database. Orcid sends a ping to one of our routes when a certain Orcid profile has been updated and this route then calls the worker.

The worker itself keeps running fine, even with the error occurring. Only this part (see below) fails over night. And it's neither the ```on_validation_error```, nor the ```on_error```... it's the catch block that's executed.

```
try {
  h->hook('import-new-' . $source)->fix_around(
    $record,
    sub {
      publication->add(
        $record,
        on_validation_error => sub {
          my ($error_rec, $errors) = @_;
          $orcid_logger->error("$orcid: Validation error: " . to_yaml($errors));
          $orcid_logger->error("$orcid: Error Rec: " . to_yaml($error_rec));
        },
        on_error => sub {
          my ($error_rec, $errors) = @_;
          $orcid_logger->error("$orcid: Other error: " . to_yaml($errors));
          $orcid_logger->error("$orcid: other error rec: " . to_yaml($error_rec));
        }
      );
    }
  );
}
catch {
  $orcid_logger->error("$orcid: Import Error: There was an error adding the rec with message $_.");
  $orcid_logger->error("$orcid: Error rec was: " . to_yaml($record));
};
```

**Comment by nics** [comment] 2021-01-25 07:42
Try to make the trycatch block as small as possible by only wrapping the publication->add. Maybe you'll get better errors then.

**Comment by nicolasfranck** [comment] 2021-01-25 11:59
It can also be caused by the age of the database handler, which is stored in a Moo attribute and not invalidated by DBI itself. That is why I proposed to use connect_cached. I'm working on that btw

**Comment by nicolasfranck** [comment] 2021-01-26 07:54
Mm, `DBI->connect_cached` cannot resolve this: its cache key depends on all connection parameters, and that changes during a transaction (`AutoCommit` is `false` during a transaction).

It seems like this only happens for the `DBD::mysql`. Mysql has a connection attribute called `mysql_auto_reconnect`, which should trigger an auto reconnect, but that does not seems to work. 

In this line https://github.com/LibreCat/Catmandu-DBI/blob/master/lib/Catmandu/Store/DBI.pm#L86 
I let `DBI::mysql` do the reconnection by itself. For other database drivers that should work.

Maybe remove that one line, and try to do the reconnection for mysql too?

**Comment by nicolasfranck** [comment] 2021-01-26 08:12
This triggers the same error:
```
use Catmandu::Sane;
use DBI;

my $dbh = DBI->connect(
    "dbi:mysql:database=librecat_main",
    "librecat",
    "librecat",
    +{
        AutoCommit => 1,
        RaiseError => 1,
        mysql_auto_reconnect => 1,
        mysql_enable_utf8 => 1
    }
);

$dbh->disconnect;
$dbh->begin_work;
```

**Comment by nicolasfranck** [comment] 2021-08-30 11:18
cf. https://github.com/perl5-dbi/DBD-mysql/issues/202

**Comment by vpeil** [comment] 2022-04-27 11:25
> @petrakohorst I hope https://github.com/LibreCat/Catmandu-DBI/tree/0.10.1 solves your issue? Options `timeout` and `reconnect_timeout` have been replaced (they generate a warning if you call their methods) by a proper reconnect on failure. The only time it does not reconnect is during a transaction, but that only happens if there is too much time between actions inside the transaction blok.

yes, this version works for us perfectly.

Hence, I'm closing this issue.

**Closed by vpeil** 2022-04-27 11:25 UTC
